version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: digi-coders-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - digi-coders-network

  # Backend API
  backend:
    build: ./backend
    container_name: digi-coders-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://admin:password123@mongodb:27017/digi-coders?authSource=admin
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/static/uploads:/app/static/uploads
    networks:
      - digi-coders-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: digi-coders-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    networks:
      - digi-coders-network

volumes:
  mongodb_data:

networks:
  digi-coders-network:
    driver: bridge
