version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: digi-coders-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - digi-coders-network-dev

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: digi-coders-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DB_URL=mongodb://admin:password123@mongodb:27017/digi-coders?authSource=admin
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - digi-coders-network-dev
    command: npm run dev

  # Frontend React App (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: digi-coders-frontend-dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - digi-coders-network-dev
    command: npm start

volumes:
  mongodb_data_dev:

networks:
  digi-coders-network-dev:
    driver: bridge
